module.exports = {
  SET_USER_TYPE: 'SET_USER_TYPE',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_PAYMENT_OPTIONS: 'SET_PAYMENT_OPTIONS',
  SET_COORDINATE: 'SET_COORDINATE',
  SET_SEARCH_RESULT: 'SET_SEARCH_RESULT',
};
